USE customer_behavior;
USE customer_behavior;

#What is the total revenue generated by male vs female customers?
SELECT gender,
       SUM(purchase_amount) AS revenue
FROM customer_shopping
GROUP BY gender;

#Which customers used discount but still spent more than the avg purchase amount?
SELECT customer_id, Purchase_Amount from customer_shopping
WHERE discount_applied = 'YES' and Purchase_Amount >= (select AVG(Purchase_Amount) FROM customer_shopping
);

#Top 5 products with highest average review rating?
SELECT item_purchased,
       ROUND(AVG(review_rating), 2) AS "Average Product Rating"
FROM customer_shopping
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

#Compare the avg purchase amount btwn standard and express shipping
SELECT shipping_type,
AVG(purchase_amount)
FROM customer_shopping
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

#Do subsrcied customers spend more?Compare avg spend and total revenue between subscribers and non-subscribers/
SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_shopping
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

#Which 5 produts have the highest percentages of purchases with discounts applied?
SELECT
    item_purchased,
    ROUND(
        100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS discount_rate
FROM customer_shopping
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

#Segment customers into New, Returning, and loyal based on their total number of previous purchases, and show the count of each segment.
SELECT
    customer_segment,
    COUNT(*) AS Number_of_customers
FROM (
    SELECT
        customer_id,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_shopping
) AS Customer_type
GROUP BY customer_segment;

#What are top 3 most purchased products within each category?
WITH item_count AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer_shopping
    GROUP BY category, item_purchased
)

SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_count
WHERE item_rank <= 3;

#Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_shopping
WHERE previous_purchases > 5
GROUP BY subscription_status;

#What is the revenue contribution of each age group?
SELECT age_group,
sum(purchase_amount) as total_revenue
from customer_shopping 
group by age_group
order by total_revenue desc;



